spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/tradingcards_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: iLoveiCode
  jpa:
    show-sql: true
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
